defaults:
  - model: BERT_NO_POOL
  - data: ACM


log:
  dir: resource/log/

model_checkpoint:
  dir: resource/model_checkpoint/

stat:
  dir: resource/stat/

tasks: [ "predict" ]

trainer:
  max_epochs: 16
  gpus: 1
  patience: 7
  min_delta: 0.05
  precision: 16
  fast_dev_run: False
  progress_bar_refresh_rate: 1
  output_dir: resource/representation/
  write_interval: epoch