defaults:
  - model: BERT_NO_POOL
  - data: ACM

log:
  dir: resource/log/

model_checkpoint:
  dir: resource/model_checkpoint/

representation:
  dir: resource/representation/
  name: ${model.name}_${data.name}.rpr
  write_interval: epoch

stat:
  dir: resource/stat/

tasks: [ "fit" ]

trainer:
  max_epochs: 16
  gpus: 1
  patience: 7
  min_delta: 0.05
  precision: 16
  fast_dev_run: False
  progress_bar_refresh_rate: 1
